### PR TITLE
msm8226 is back again

### PR DESCRIPTION
**Pull request by sub77**

### CODE REVIEW

**Comment by M1cha** [comment]
this commit doesn't make any sense and the arguments are wrong.
Can you explain what you tried to do here?

**Comment by sub77** [comment]
i tried to get my falcon working again since the mmap api changes you comitted in january. without this commit my two msm8226 devices (moto g 2013 and galaxy tab4) stopped booting uefi completly.

**Comment by M1cha** [comment]
this may be true but this commit only works by accident. I mean look at it. you're completely ignoring the argument order and you only don't see errors because all arguments are of type int.

**Comment by sub77** [comment]
for sure, iam a compiler only, no dev. just had a look at the mmap parameters before the api change and now it is working again.

**Comment by z3ntu** [comment]
> this commit doesn't make any sense and the arguments are wrong.

> Got uefi booting with efidroid/bootloader_lk#19

lol

**Comment by sub77** [comment]
https://github.com/efidroid/bootloader_lk/pull/21

**Comment by sub77** [comment]
[https://github.com/efidroid/bootloader_lk/pull/21](https://github.com/efidroid/bootloader_lk/issues/21)

**Comment by joe2k01** [comment]
@z3ntu He gave me the file he used and I referenced the wrong commit

**Pull request closed without merging**
