### PR TITLE
Adding mipi_dsi_cmd_mode_config definition

### PR DESCRIPTION
**Pull request by gamelaster**

### CODE REVIEW

**Comment by M1cha** [comment]
why is this needed? It looks like it's used by msm7627a only which isn't supported at all.

**Comment by feherneoh** [comment]
Then what is the correct function to be used by CMD mode panels? Only the video mode version is used by newer targets, as they all have video panels specified

**Comment by M1cha** [comment]
well the change itself seems fine, I'm just interested in what he tries to do so I know if we really need it or not. (I don't want changes in LK which aren't used by anybody, to make the history more clear)

**Comment by gamelaster** [comment]
we actually using it (but in custom panel drivers for msm8960)

**Pull request merged**
